version: 3

tasks:
  format:
    desc: Format the codebase
    cmds:
      - uv run black ontoshacl/
      - uv run isort ontoshacl/

  lint:
    desc: Lint the codebase
    cmd: uv run ruff check --fix ontoshacl/

  test:minimal:
    desc: Run minimal test case
    cmds:
      - uv run ontoshacl --config tests/test-minimal-config.json
      - uv run pyshacl --shapes tests/validators/valpub.ttl tests/output/test-minimal.ttl

  test:rico:
    desc: Run rico test case
    cmds:
      - uv run ontoshacl --config tests/test-rico-config.json
      - uv run pyshacl --shapes tests/validators/valpub.ttl tests/output/test-rico.ttl
      - uv run pyshacl --shapes tests/output/test-rico.ttl tests/data/rico-valid.ttl

  test:
    desc: Run all tests
    cmds:
      - task: test:minimal
      - task: test:rico
