version: 3

tasks:
  format:
    desc: Format the codebase
    cmds:
      - uv run black ontoshacl/
      - uv run isort ontoshacl/

  lint:
    desc: Lint the codebase
    cmd: uv run ruff check --fix ontoshacl/

  test:
    desc: Run Test case
    cmds:
      - uv run ontoshacl --config tests/config.json
